parameters:
- name: location  # defaults for any parameters that aren't specified
  default: ''
- name: envName
  default: ''
- name: azureSub
  default: ''
- name: templateName
  default: ''
- name: deploymentName
  default: ''


steps:
      - task: AzureCLI@2
        displayName: Deploy template ${{ parameters.templateName }} to ${{ parameters.location }}
        inputs:
          azureSubscription: '${{ parameters.azureSub }}'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az --version
            az deployment sub create \
            --name '${{ parameters.deploymentName }}-${{ parameters.envName }}-${{ parameters.location }}' \
            --location ${{ parameters.location }} \
            --template-file '${{ parameters.templateName }}.bicep' \
            --parameters './parameters/${{ parameters.templateName }}-parameters-${{ parameters.envName }}.json' \
            --parameters env=${{ parameters.envName }} location=${{ parameters.location }}
          workingDirectory: './templates/IaC/'