parameters:
- name: environmentName
  default: ''
- name: deploymentName
  default: ''
- name: region
  default: ''
- name: azureServiceConnection
  default: ''
- name: secretName
  default: ''
- name: secretValue
  default: ''


steps:
  - task: AzureCLI@2
    displayName: 'Add key ${{ parameters.secretName }} to kv-shared-${{ parameters.environmentName }}-${{ parameters.region }}'
    inputs:
      azureSubscription: '${{ parameters.azureServiceConnection }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az --version
        az keyvault secret set --vault-name 'kv-shared-${{ parameters.environmentName }}-${{ parameters.region }}' \
        --name '${{ parameters.secretName }}' \
        --value '${{ parameters.secretValue }}'