parameters:
- name: environmentName
  type: string
  default: ''
- name: deploymentName
  type: string
  default: ''
- name: region
  type: string
  default: ''
- name: azureServiceConnection
  type: string
  default: ''
- name: variableGroup
  type: object

jobs:
- job: ${{ parameters.deploymentName }}_keyvault_${{ parameters.environmentName }}_${{ parameters.region }}_job
  variables:
  - template: ../variables/shared-variables.yml@sharedTemplates
  - group: ${{ parameters.deploymentName }}-inputVariables-${{ parameters.environmentName }}
  steps:
  - ${{ each variable in parameters.variableGroup }}:  
    - template: ../tasks/keyvault-add_secrets-task.yml@sharedTemplates
      parameters:
        environmentName: ${{ parameters.environmentName }}
        region: ${{ parameters.region }}
        deploymentName: ${{ parameters.deploymentName }}
        azureServiceConnection: ${{ parameters.azureServiceConnection }}
        secretName: ${{ variable }}
        secretValue: $(${{ variable }})