parameters:
- name: deploymentName
  type: string
- name: environmentName
  type: string
- name: regions
  type: object
- name: variableGroup
  type: object

stages:
- stage: ${{ parameters.deploymentName }}_keyvault_${{ parameters.environmentName }}_stage
  variables:
  - template: ../variables/shared-variables.yml@sharedTemplates
  
  jobs:
  - ${{ each region in parameters.regions }}:
    - template: ../jobs/keyvault-add_secrets-job.yml@sharedTemplates
      parameters:
        environmentName: ${{ parameters.environmentName }}
        region: ${{ region }}
        deploymentName: ${{ parameters.deploymentName }}
        azureServiceConnection: ${{ variables.azureServiceConnection }}
        variableGroup: ${{ parameters.variableGroup }}
